### ISSUE TITLE
CUDA errors?

### ISSUE THREAD

**Issue by patrikpatrik** [VectorSpaceLab/OmniGen2#38]
Not sure what I did wrong, but I did notice when I run python app.py the safetensors aren't downloaded?

```
Exception raised from c10_cuda_check_implementation at C:\actions-runner\_work\pytorch\pytorch\pytorch\c10\cuda\CUDAException.cpp:43 (most recent call first):
00007FF96FDD2C2400007FF96FDD2B80 c10.dll!c10::Error::Error [<unknown file> @ <unknown line number>]
00007FF96FDD170A00007FF96FDD16B0 c10.dll!c10::detail::torchCheckFail [<unknown file> @ <unknown line number>]
00007FF990306BBF00007FF9903068B0 c10_cuda.dll!c10::cuda::c10_cuda_check_implementation [<unknown file> @ <unknown line number>]
00007FFFDEA8261300007FFFDE97CB70 flash_attn_2_cuda.cp311-win_amd64.pyd!PyInit_flash_attn_2_cuda [<unknown file> @ <unknown line number>]
00007FFFDEA877A100007FFFDE97CB70 flash_attn_2_cuda.cp311-win_amd64.pyd!PyInit_flash_attn_2_cuda [<unknown file> @ <unknown line number>]
00007FFFDEA8431700007FFFDE97CB70 flash_attn_2_cuda.cp311-win_amd64.pyd!PyInit_flash_attn_2_cuda [<unknown file> @ <unknown line number>]
00007FFFDEA817A100007FFFDE97CB70 flash_attn_2_cuda.cp311-win_amd64.pyd!PyInit_flash_attn_2_cuda [<unknown file> @ <unknown line number>]
00007FFFDE9769B000007FFFDE965FE0 flash_attn_2_cuda.cp311-win_amd64.pyd!c10::ivalue::Object::operator= [<unknown file> @ <unknown line number>]
00007FFFDE985C1900007FFFDE97CB70 flash_attn_2_cuda.cp311-win_amd64.pyd!PyInit_flash_attn_2_cuda [<unknown file> @ <unknown line number>]
00007FFFDE98351A00007FFFDE97CB70 flash_attn_2_cuda.cp311-win_amd64.pyd!PyInit_flash_attn_2_cuda [<unknown file> @ <unknown line number>]
00007FFFDE9835F400007FFFDE97CB70 flash_attn_2_cuda.cp311-win_amd64.pyd!PyInit_flash_attn_2_cuda [<unknown file> @ <unknown line number>]
00007FFFDE96EF9B00007FFFDE965FE0 flash_attn_2_cuda.cp311-win_amd64.pyd!c10::ivalue::Object::operator= [<unknown file> @ <unknown line number>]
00007FF97258BD5C00007FF97258B020 python311.dll!PyCFunction_GetFlags [<unknown file> @ <unknown line number>]
00007FF97254506100007FF972544F40 python311.dll!PyObject_MakeTpCall [<unknown file> @ <unknown line number>]
```

**Comment by able2608** [comment]
There are prebuilt flash attention wheels for Windows, just not on pypi though. If it is not done yet go get one [here](https://huggingface.co/lldacing/flash-attention-windows-wheel).
It is normal for flash attention to build for more than a couple of hours for some reason. I have experience once that took me a full night (around 7 hours).

**Comment by patrikpatrik** [comment]
Thanks for the heads up. I tried the prebuilt ones but thats when I got the CUDA errors. For some reason when I run python app.py it doesn't seem to download safetensors like it did the 1st time. Currently on my 14th installation and it skips those files even though I already deleted that folder and conda clean everything and pip cache purged everything.

**Comment by able2608** [comment]
Hugging Face cache is not located in the installation folder, but rather in your user cache (at `C:\Users\[your user name]\.cache\huggingface\hub`. To force a redownload you need to clean it there (find the folder with the name OmniGen2 and delete it). However some users report that they are not able to get auto download working, in that case you'll need to manually download all the things. See https://github.com/VectorSpaceLab/OmniGen2/issues/27#issuecomment-3003491388 for more instructions on manual download.

**Comment by patrikpatrik** [comment]
> Hugging Face cache is not located in the installation folder, but rather in your user cache (at `C:\Users\[your user name]\.cache\huggingface\hub`). To force a redownload you need to clean it there (find the folder with the name OmniGen2 and delete it).

That worked! Thanks so much @able2608. After waiting 7.5 hours for flash-attn to finish and redownloading all those tensors it now works and having a blast. I will close this issue cheers~
